name: Build Project

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  Build_Release:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build Release
        shell: bash
        run: '"C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Msbuild/Current/Bin/MSBuild.exe" -property:Configuration=Release -property:PlatformToolset=v143'

      - name: Build Release_Version
        shell: bash
        run: '"C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Msbuild/Current/Bin/MSBuild.exe" -property:Configuration=Release_Version -property:PlatformToolset=v143'

      - name: Package Release Builds
        shell: cmd
        run: |
          move /y Release\TerraMenu.dll TerraMenu.dll
          move /y Release_Version\version.dll version.dll

          mkdir BepInEx\plugins
          copy TerraMenu.dll BepInEx\plugins\TerraMenu.dll

          tar -caf TerraMenu-Release.zip BepInEx\ TerraMenu.dll version.dll LICENSE

          tar -caf TerraMenu-Install.zip version.dll LICENSE

      - name: Upload Release Zip
        uses: actions/upload-artifact@v4.2.0
        with:
          name: Release-zip
          path: TerraMenu-Release.zip

      - name: Upload Install Zip
        uses: actions/upload-artifact@v4.2.0
        with:
          name: Install-zip
          path: TerraMenu-Install.zip

      - name: Upload version.dll
        uses: actions/upload-artifact@v4.2.0
        with:
          name: Release-dll
          path: version.dll

  Build_Debug:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build Debug
        shell: bash
        run: '"C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Msbuild/Current/Bin/MSBuild.exe" -property:Configuration=Debug -property:PlatformToolset=v143'

      - name: Build Debug_Version
        shell: bash
        run: '"C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Msbuild/Current/Bin/MSBuild.exe" -property:Configuration=Debug_Version -property:PlatformToolset=v143'

      - name: Package Debug Builds
        shell: cmd
        run: |
          move /y Debug\TerraMenu.dll TerraMenu.dll
          move /y Debug_Version\version.dll version.dll
          tar -caf TerraMenu-Debug.zip TerraMenu.dll version.dll LICENSE

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4.2.0
        with:
          name: Debug
          path: TerraMenu-Debug.zip

  AutoRelease:
    runs-on: windows-2022
    needs: [Build_Release, Build_Debug]
    steps:
      - name: Download Release Zip
        uses: actions/download-artifact@v4.1.7
        with:
          name: Release-zip

      - name: Download Install Zip
        uses: actions/download-artifact@v4.1.7
        with:
          name: Install-zip

      - name: Download version.dll
        uses: actions/download-artifact@v4.1.7
        with:
          name: Release-dll

      - name: Download Debug Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: Debug

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        id: "automatic_releases"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            TerraMenu-Release.zip
            TerraMenu-Install.zip
            version.dll
            TerraMenu-Debug.zip
